name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run typecheck
        run: yarn typecheck

      - name: Run lint
        run: yarn lint
